// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	cfforeach "github.com/mike-carey/cf-foreach"
)

type FakeCFForEach struct {
	ServiceBindingToAppStub        func([]cfclient.ServiceBinding) ([]cfclient.App, []error)
	serviceBindingToAppMutex       sync.RWMutex
	serviceBindingToAppArgsForCall []struct {
		arg1 []cfclient.ServiceBinding
	}
	serviceBindingToAppReturns struct {
		result1 []cfclient.App
		result2 []error
	}
	serviceBindingToAppReturnsOnCall map[int]struct {
		result1 []cfclient.App
		result2 []error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCFForEach) ServiceBindingToApp(arg1 []cfclient.ServiceBinding) ([]cfclient.App, []error) {
	var arg1Copy []cfclient.ServiceBinding
	if arg1 != nil {
		arg1Copy = make([]cfclient.ServiceBinding, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.serviceBindingToAppMutex.Lock()
	ret, specificReturn := fake.serviceBindingToAppReturnsOnCall[len(fake.serviceBindingToAppArgsForCall)]
	fake.serviceBindingToAppArgsForCall = append(fake.serviceBindingToAppArgsForCall, struct {
		arg1 []cfclient.ServiceBinding
	}{arg1Copy})
	fake.recordInvocation("ServiceBindingToApp", []interface{}{arg1Copy})
	fake.serviceBindingToAppMutex.Unlock()
	if fake.ServiceBindingToAppStub != nil {
		return fake.ServiceBindingToAppStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.serviceBindingToAppReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCFForEach) ServiceBindingToAppCallCount() int {
	fake.serviceBindingToAppMutex.RLock()
	defer fake.serviceBindingToAppMutex.RUnlock()
	return len(fake.serviceBindingToAppArgsForCall)
}

func (fake *FakeCFForEach) ServiceBindingToAppCalls(stub func([]cfclient.ServiceBinding) ([]cfclient.App, []error)) {
	fake.serviceBindingToAppMutex.Lock()
	defer fake.serviceBindingToAppMutex.Unlock()
	fake.ServiceBindingToAppStub = stub
}

func (fake *FakeCFForEach) ServiceBindingToAppArgsForCall(i int) []cfclient.ServiceBinding {
	fake.serviceBindingToAppMutex.RLock()
	defer fake.serviceBindingToAppMutex.RUnlock()
	argsForCall := fake.serviceBindingToAppArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCFForEach) ServiceBindingToAppReturns(result1 []cfclient.App, result2 []error) {
	fake.serviceBindingToAppMutex.Lock()
	defer fake.serviceBindingToAppMutex.Unlock()
	fake.ServiceBindingToAppStub = nil
	fake.serviceBindingToAppReturns = struct {
		result1 []cfclient.App
		result2 []error
	}{result1, result2}
}

func (fake *FakeCFForEach) ServiceBindingToAppReturnsOnCall(i int, result1 []cfclient.App, result2 []error) {
	fake.serviceBindingToAppMutex.Lock()
	defer fake.serviceBindingToAppMutex.Unlock()
	fake.ServiceBindingToAppStub = nil
	if fake.serviceBindingToAppReturnsOnCall == nil {
		fake.serviceBindingToAppReturnsOnCall = make(map[int]struct {
			result1 []cfclient.App
			result2 []error
		})
	}
	fake.serviceBindingToAppReturnsOnCall[i] = struct {
		result1 []cfclient.App
		result2 []error
	}{result1, result2}
}

func (fake *FakeCFForEach) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.serviceBindingToAppMutex.RLock()
	defer fake.serviceBindingToAppMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCFForEach) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cfforeach.CFForEach = new(FakeCFForEach)
